#!/bin/bash

friends=$1
stranger=`cat`
n=`./count < ${friends}`

for (( c=1; c<=n; c++ ))
do
	friend=`./nth ${friends} ${c}`
	success=`echo "${friend} ${stranger}" | isofilter | grep "kept=1"`
	if [ "$success" != "" ]
	then
		echo "$c"
		break
	fi
done
